name: CI
on:
  workflow_dispatch:
  pull_request:

  # triggering CI on the default branch improves caching
  # see https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
  push:
    branches:
      - main

jobs:
  worker-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: everything
      - run: |
          shopt -s dotglob
          mv everything/worker/* .
          rm -Rf everything
          ls -la
      - uses: guardian/setup-scala@v1
      - run: sbt -v test

  test-capture:
    uses: ./.github/workflows/reusable-capture.yml
    permissions: { id-token: write, contents: read }
    with:
      LOGIC_CAPTURE_FILE: "sample-project/logic-capture.yml"
    secrets:
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
