name: MicroPython Logic Capture Workflow

on:
  workflow_call:
    inputs:
      STUFF_NAME:
        description:
          "The good stuff man"
        default: 'boom'
        required: false
        type: string

jobs:
  deploy-and-capture:
    runs-on: pico-logic
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v4
      - name: Say hi
        run: |
          pip install logic2-automation
          
          pipx install mpremote
          mpremote version
          echo "Gosh"
